### ISSUE TITLE
Process failed when submitting URL

### ISSUE THREAD

**Issue by supahal** [cuckoobox/cuckoo#463]
Traceback (most recent call last):
  File "./process.py", line 124, in <module>
    main()
  File "./process.py", line 115, in main
    autoprocess(parallel=args.parallel)
  File "./process.py", line 83, in autoprocess
    sample = db.view_sample(task.sample_id)
  File "/home/tmirt/tools/cuckoo/utils/../lib/cuckoo/common/utils.py", line 267, in inner
    return f(self, *args, **kwargs)
  File "/home/tmirt/tools/cuckoo/utils/../lib/cuckoo/core/database.py", line 1105, in view_sample
    sample = session.query(Sample).get(sample_id)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 818, in get
    if len(ident) != len(mapper.primary_key):
TypeError: object of type 'NoneType' has no len()

Test Case:
1. Submit case by url:
eg.:
https://www.virustotal.com/intelligence/download/?sha256=de633994b6217e2d5dfe38d48a6caf0b248d4fe0f60812953052841cef77ae61

2. Process result should be turn off (process result on a new thread)

**Comment by supahal** [comment]
Just found out:
Upon checking tasks db.

ID     | Category| Status | Samle Id
| 107 | url      | completed |      NULL |
| 108 | url      | completed |      NULL |

this will produce exception.

**Comment by jekil** [comment]
Confirmed bug, thank you very much for reporting. I am going to fix it.
