### ISSUE TITLE
AttributeError with NetworkAnalysis module

### ISSUE THREAD

**Issue by cptkaos** [cuckoobox/cuckoo#479]
Anybody run into this recently with latest repo?

2015-02-23 17:02:36,510 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "NetworkAnalysis":
Traceback (most recent call last):
  File "/data/cuckoo/lib/cuckoo/core/plugins.py", line 186, in process
    data = current.run()
  File "/data/cuckoo/modules/processing/network.py", line 593, in run
    sort_pcap(self.pcap_path, sorted_path)
  File "/data/cuckoo/modules/processing/network.py", line 701, in sort_pcap
    batch_sort(inc, outpath, output_class=lambda path: SortCap(path, linktype=inc.linktype))
  File "/data/cuckoo/modules/processing/network.py", line 632, in batch_sort
    current_chunk = list(islice(input_iterator,buffer_size))
  File "/data/cuckoo/modules/processing/network.py", line 688, in next
    sip, dip, sport, dport, proto = flowtuple_from_raw(raw, self.linktype)
  File "/data/cuckoo/modules/processing/network.py", line 713, in flowtuple_from_raw
    sport, dport = l3.sport, l3.dport
AttributeError: 'str' object has no attribute 'sport'

**Comment by cptkaos** [comment]
Please ignore. Clean up in network.py ? (it looks like it is done in the latest module version):

 pkt = dpkt.ethernet.Ethernet(raw)
 ip = pkt.data

 if isinstance(ip, dpkt.ip.IP):
 sip, dip = ip.src, ip.dst
 proto = ip.p

 if proto == dpkt.ip.IP_PROTO_TCP or proto == dpkt.ip.IP_PROTO_UDP:
 l3 = ip.data
 sport, dport = l3.sport, l3.dport
 else:
 sport, dport = 0, 0

 else:
 sip, dip, proto = 0, 0, 1
 sport, dport = 0, 0

**Comment by cptkaos** [comment]
I would recommend pulling down commit on 01/26 which seems to work fine.

**Comment by jekil** [comment]
Closed because it seems already fixed
