### ISSUE TITLE
Exception when processing NetworkAnalysis

### ISSUE THREAD

**Issue by supahal** [cuckoobox/cuckoo#500]
This will occur when dump.pcap is not created/no file found

2015-03-18 09:27:37,790 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "NetworkAnalysis":
Traceback (most recent call last):
  File "/home/tmirt/tools/cuckoo-tmp/lib/cuckoo/core/plugins.py", line 186, in process
    data = current.run()
  File "/home/tmirt/tools/cuckoo-tmp/modules/processing/network.py", line 593, in run
    sort_pcap(self.pcap_path, sorted_path)
  File "/home/tmirt/tools/cuckoo-tmp/modules/processing/network.py", line 708, in sort_pcap
    batch_sort(inc, outpath, output_class=lambda path: SortCap(path, linktype=inc.linktype))
  File "/home/tmirt/tools/cuckoo-tmp/modules/processing/network.py", line 635, in batch_sort
    current_chunk = list(islice(input_iterator,buffer_size))
  File "/home/tmirt/tools/cuckoo-tmp/modules/processing/network.py", line 677, in __iter__
    self.fd = dpkt.pcap.Reader(open(self.name, "rb"))
IOError: [Errno 2] No such file or directory: '/home/tmirt/tools/cuckoo-tmp/storage/analyses/1/dump.pcap'

**Comment by jekil** [comment]
Thanks for reporting.
