### ISSUE TITLE
REST API doesn't work properly in master

### ISSUE THREAD

**Issue by mzweilin** [cuckoobox/cuckoo#586]
It seems the porting work to Flask hasn't finished yet. I encountered one serious problem in submitting files, which was not expected in the master branch.

The code should be tested properly before being merged to master. https://github.com/cuckoobox/cuckoo/commit/65e4491a3c26434bec196a5eaecfccaadd93be71#diff-3d03530109e7e7620d069801fbdbedf5

Flask has a different interface in reading POST request. Here's a modified version that works for me. (I just need to submit file without any parameters. Thus I did not try parsing the parameters.)
```
@app.route("/tasks/create/file", methods=["POST",])
@app.route("/v1/tasks/create/file", methods=["POST",])
def tasks_create_file():
    data = request.files['file']
    package = request.form.get("package", "")
    timeout = request.form.get("timeout", "")
    priority = request.form.get("priority", 1)
    options = request.form.get("options", "")
    machine = request.form.get("machine", "")
    platform = request.form.get("platform", "")
    tags = request.form.get("tags", None)
    custom = request.form.get("custom", "")
    owner = request.form.get("owner", "")
    memory = request.form.get("memory", False)
    clock = request.form.get("clock", None)

    if memory:
        memory = True
    enforce_timeout = request.form.get("enforce_timeout", False)
    if enforce_timeout:
        enforce_timeout = True

    temp_file_path = store_temp_file(data.read(), data.filename)
    task_id = db.add_path(
        file_path=temp_file_path,
        package=package,
        timeout=timeout,
        priority=priority,
        options=options,
        machine=machine,
        platform=platform,
        tags=tags,
        custom=custom,
        owner=owner,
        memory=memory,
        enforce_timeout=enforce_timeout,
        clock=clock
    )

    return jsonify(task_id=task_id)
```

**Comment by jbremer** [comment]
You're right, the new `api.py` is has yet to be finished. @botherder might pick up where you left off? Either that or put it in a new branch, as-is it's just completely broken.

**Comment by mzweilin** [comment]
I wonder if there's similar problem in process.py. I encountered the error message as below with the current version.

```
ERROR:sqlalchemy.pool.QueuePool:Exception during reset or similar
Traceback (most recent call last):
  File "/home/xuweilin/.local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 631, in _finalize_fairy
    fairy._reset(pool)
  File "/home/xuweilin/.local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 771, in _reset
    pool._dialect.do_rollback(self)
  File "/home/xuweilin/.local/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2519, in do_rollback
    dbapi_connection.rollback()
ProgrammingError: (2014, "Commands out of sync; you can't run this command now")
    util.raise_from_cause(err)
  File "/home/xuweilin/.local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/xuweilin/.local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 51, in instances
    for query_entity in query._entities
  File "/home/xuweilin/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3311, in row_processor
    polymorphic_discriminator=self._polymorphic_discriminator
  File "/home/xuweilin/.local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 313, in _instance_processor
    getter = result._getter(col)
  File "/home/xuweilin/.local/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 495, in _getter
    return self._metadata._getter(key)
AttributeError: 'NoneType' object has no attribute '_getter'
Traceback (most recent call last):
  File "./utils/process.py", line 149, in <module>
    main()
  File "./utils/process.py", line 140, in main
    autoprocess(parallel=args.parallel)
  File "./utils/process.py", line 120, in autoprocess
    pool.join()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 460, in join
    assert self._state in (CLOSE, TERMINATE)
AssertionError

```

**Comment by jbremer** [comment]
If I'm not mistaken I've fixed this particular error in the `monitor` branch along with an attempt to fix some other errors as well.

**Comment by botherder** [comment]
Yes, I'm still to finish the Flask port. Working on it.

**Comment by botherder** [comment]
This should be fixed now.

**Comment by mzweilin** [comment]
Thanks @jbremer  and @botherder . 

@jbremer , when are you going to merge the monitor branch? If it will not be soon, I would prefer keeping the old stable version of master in my running instance.
