### ISSUE TITLE
Error volatility module when create report

### ISSUE THREAD

**Issue by chikiru900** [cuckoobox/cuckoo#600]
I have a error when analysis with cuckoo 1.2

2015-07-12 21:52:41,711 [volatility.utils] DEBUG: Trying <class 'volatility.plugins.addrspaces.macho.MachOAddressSpace'> 
2015-07-12 21:52:41,712 [volatility.utils] DEBUG: Trying <class 'volatility.plugins.addrspaces.lime.LimeAddressSpace'> 
2015-07-12 21:52:41,712 [volatility.utils] DEBUG: Trying <class 'volatility.plugins.addrspaces.hibernate.WindowsHiberFileSpace32'> 
2015-07-12 21:52:41,714 [volatility.utils] DEBUG: Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2015-07-12 21:52:41,716 [volatility.utils] DEBUG: Trying <class 'volatility.plugins.addrspaces.hpak.HPAKAddressSpace'> 
2015-07-12 21:52:41,717 [volatility.utils] DEBUG: Trying <class 'volatility.plugins.addrspaces.vboxelf.VirtualBoxCoreDumpElf64'> 
2015-07-12 21:52:41,717 [volatility.utils] DEBUG: Trying <class 'volatility.plugins.addrspaces.vmware.VMWareSnapshotFile'> 
2015-07-12 21:52:41,718 [volatility.utils] DEBUG: Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2015-07-12 21:52:41,718 [volatility.utils] DEBUG: Trying <class 'volatility.plugins.addrspaces.amd64.AMD64PagedMemory'> 
2015-07-12 21:52:41,719 [volatility.utils] DEBUG: Trying <class 'volatility.plugins.addrspaces.intel.IA32PagedMemoryPae'> 
2015-07-12 21:52:41,719 [volatility.utils] DEBUG: Trying <class 'volatility.plugins.addrspaces.intel.IA32PagedMemory'> 
2015-07-12 21:52:41,720 [volatility.utils] DEBUG: Trying <class 'volatility.plugins.addrspaces.standard.FileAddressSpace'> 
2015-07-12 21:52:41,720 [volatility.utils] DEBUG: Trying <class 'volatility.plugins.addrspaces.arm.ArmAddressSpace'> 
2015-07-12 21:52:42,224 [modules.processing.memory] ERROR: Generic error executing volatility
Traceback (most recent call last):
  File "/home/mvs/Desktop/cuckoo-1.2/modules/processing/memory.py", line 1047, in run
    results = vol.run()
  File "/home/mvs/Desktop/cuckoo-1.2/modules/processing/memory.py", line 983, in run
    results["mutantscan"] = vol.mutantscan()
  File "/home/mvs/Desktop/cuckoo-1.2/modules/processing/memory.py", line 757, in mutantscan
    header = mutant.get_object_header()
AttributeError: 'tuple' object has no attribute 'get_object_header'

**Comment by jbremer** [comment]
Could you please share with us the version of your Volatility, Windows version, and any other information that we might require to reproduce this issue?

**Comment by ykorkmaz** [comment]
I had the same error, I think I had this error because my volatility and yara installations were old. After installing/updating the volatility and yara, my problem was resolved.

**Comment by jbremer** [comment]
I guess @ykorkmaz answer suffices for now. @chikiru900 Please update to the latest version(s) and if you get any other errors, please provide us with the version numbers etc.

**Comment by dreamerdamzel** [comment]
Hello, 
I have installed cuckoo 2.0
and volatility- 2.6
virtualization software - Oracle Virtual Box
I get the memory dump file but the volatility does not do any analysis it gives me the following error 

2017-03-24 17:06:56,511 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 10010 (interface=vboxnet0, host=192.168.56.101, pcap=/home/labuser/cuckoo/storage/analyses/29/dump.pcap)
2017-03-24 17:07:10,006 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=ubuntu 16, ip=192.168.56.101)
2017-03-24 17:07:28,786 [lib.cuckoo.core.guest] INFO: ubuntu 16: analysis completed successfully
2017-03-24 17:08:06,962 [modules.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label ubuntu 16 to path /home/labuser/cuckoo/storage/analyses/29/memory.dmp
2017-03-24 17:08:22,221 [modules.processing.memory] ERROR: Generic error executing volatility
Traceback (most recent call last):
  File "/home/labuser/cuckoo/modules/processing/memory.py", line 1036, in run
    results = VolatilityManager(self.memory_path).run(manager=machine_manager, vm=task_machine)
  File "/home/labuser/cuckoo/modules/processing/memory.py", line 948, in run
    vol = VolatilityAPI(self.memfile, self.osprofile)
  File "/home/labuser/cuckoo/modules/processing/memory.py", line 59, in __init__
    self.init_config()
  File "/home/labuser/cuckoo/modules/processing/memory.py", line 115, in init_config
    if self.get_dtb():
  File "/home/labuser/cuckoo/modules/processing/memory.py", line 65, in get_dtb
    for ep in ps.calculate():
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/plugins/filescan.py", line 354, in calculate
    addr_space = utils.load_as(self._config, astype = 'physical')
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/utils.py", line 65, in load_as
    raise error
AddrSpaceError: No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 QemuCoreDumpElf: No base Address Space
 VMWareAddressSpace: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 Win10AMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 FileAddressSpace - EXCEPTION: 'DW_AT_byte_size'
 ArmAddressSpace: No base Address Space

2017-03-24 17:08:35,378 [lib.cuckoo.core.scheduler] INFO: Task #29: reports generation completed (path=/home/labuser/cuckoo/storage/analyses/29)
2017-03-24 17:08:35,469 [lib.cuckoo.core.scheduler] INFO: Task #29: analysis procedure completed

I have created the profile in my Ubuntu 16.10 VM (guest) and then added into the volatility profiles directory in my host Ubuntu 16.10. 
I have done all the configuration properly in the cuckoo, but the error still persists.
Can anyone please help me with this issue.

Thanks
