### ISSUE TITLE
1st time lunching cuckoo 1.2 issues

### ISSUE THREAD

**Issue by alialk** [cuckoobox/cuckoo#612]
hi there
i just started installing cuckoo and launching it but when i finished the whole installation processes and everything i got stuck with these errors i would really appreciate your help on this ASAP since am working on developing it for my university final year project
---------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "cuckoo.py", line 101, in <module>
    test=args.test)
  File "cuckoo.py", line 59, in cuckoo_init
    init_modules()
  File "/opt/cuckoo/lib/cuckoo/core/startup.py", line 198, in init_modules
    import_package(modules.processing)
  File "/opt/cuckoo/lib/cuckoo/core/plugins.py", line 43, in import_package
    import_plugin(name)
  File "/opt/cuckoo/lib/cuckoo/core/plugins.py", line 30, in import_plugin
    module = __import__(name, globals(), locals(), ["dummy"], -1)
  File "/opt/cuckoo/modules/processing/memory.py", line 18, in <module>
    import volatility.plugins.malware.apihooks as apihooks
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.4-py2.7.egg/volatility/plugins/malware/apihooks.py", line 160, in <module>
    class Hook(object):
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.4-py2.7.egg/volatility/plugins/malware/apihooks.py", line 167, in Hook
    decode_bits = distorm3.Decode32Bits):
NameError: name 'distorm3' is not defined
---------------------------------------------------------------------------------------------------------------------

**Comment by mcpacosy** [comment]
The module apihooks.py of volatility needs the distorm3 Python package. Did you install distorm3? You can check if it is available on your system with the following command in a console:

```
$ python -c "import distorm3"
```
This should NOT rais an ImportError. If it does then you must install distorm3 e.g. with pip:

```
$ sudo pip install distorm3
```

HTH

**Comment by alialk** [comment]
yeah you are right man 
i didn't download the distorm3 
i just installed now and its working perfectly
