### ISSUE TITLE
Three errors I cannot figure out

### ISSUE THREAD

**Issue by galaftion** [cuckoobox/cuckoo#623]
Hello everyone,

I got cuckoo to work but there are three errors that come up once in a while when the extension of the submitted file is not specifically identified (identifiable).

Any help is greatly appreciated:

**********************************
ERROR#1
2015-08-17 13:43:47,798 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "BehaviorAnalysis":
Traceback (most recent call last):
  File "/home/examiner/cuckoo/lib/cuckoo/core/plugins.py", line 195, in process
    data = current.run()
  File "/home/examiner/cuckoo/modules/processing/behavior.py", line 1106, in run
    for call in process["calls"]:
  File "/home/examiner/cuckoo/modules/processing/behavior.py", line 191, in next
    return self.cacheless_next()
  File "/home/examiner/cuckoo/modules/processing/behavior.py", line 168, in cacheless_next
    self.wait_for_lastcall()
  File "/home/examiner/cuckoo/modules/processing/behavior.py", line 146, in wait_for_lastcall
    if not self.parser.read_next_message():
  File "/home/examiner/cuckoo/lib/cuckoo/common/netlog.py", line 195, in read_next_message
    self.handler.log_call(context, apiname, category, arguments)
  File "/home/examiner/cuckoo/modules/processing/behavior.py", line 252, in log_call
    returnval] + arguments)
  File "/home/examiner/cuckoo/modules/processing/behavior.py", line 311, in _parse
    pretty = pretty_print_arg(category, api_name, arg_name, argument["value"])
  File "/home/examiner/cuckoo/lib/cuckoo/common/utils.py", line 1252, in pretty_print_arg
    val = int(arg_val, 16)
ValueError: invalid literal for int() with base 16: '0x-7ffffffe'

OBS: The analysis completes and a report is generated.

ERROR#2
2015-08-17 13:43:49,265 [modules.processing.memory] ERROR: Generic error executing volatility
Traceback (most recent call last):
  File "/home/examiner/cuckoo/modules/processing/memory.py", line 1063, in run
    vol = VolatilityManager(self.memory_path)
  File "/home/examiner/cuckoo/modules/processing/memory.py", line 927, in __init__
    for pid in self.voptions.mask.pid_generic.split(","):
AttributeError: 'int' object has no attribute 'split'

OBS: The analysis completes and a report is generated.

ERROR#3
2015-08-17 13:43:50,942 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/examiner/cuckoo/lib/cuckoo/core/scheduler.py", line 430, in run
    self.process_results()
  File "/home/examiner/cuckoo/lib/cuckoo/core/scheduler.py", line 373, in process_results
    RunSignatures(task=self.task.to_dict(), results=results).run()
  File "/home/examiner/cuckoo/lib/cuckoo/core/plugins.py", line 400, in run
    for proc in self.results["behavior"]["processes"]:
KeyError: 'behavior'

OBS: This last one is particularly annoying since it breaks the entire analysis and cannot get to the point where I can have a final report (even if partial). The generated data is available in storage.

I tun latest version of cuckoo, properly installed on a Linux box (Ubuntu up to date v3.19.0-26). The analysis machine is a Win7 Enterprise x64 SP1. Python v2.7 on both sides. 

I mention the fact that if I specify the file extension (renaming the file) everything works just fine except (sometimes) volatility error. I re-installed Volatility several times (v2.4) which works just fine offline. 

Many thx in advance

**Comment by brad-accuvant** [comment]
You aren't using the upstream Cuckoo, as is clear from the reported tracebacks.  Please don't report these issues to them as I'm sure it's annoying to them and wastes their time.

**Comment by galaftion** [comment]
annoying ? wasting their time ? wow ! sorry for asking. I thought that community supported plugins (which are obviously used in this case) are posted on github with the goal of improving this amazing tool  and bring recognition to coders. I was wrong, obviously. According to you at least . thx for your very "useful and helpful" input. Anyone else please, could point me in the right direction ? with no judgement and reprisal ...lol..thx in advance

**Comment by jbremer** [comment]
Which version of Cuckoo are you running? Any special samples or code modifications that you've done to get these errors?

**Comment by brad-accuvant** [comment]
He's using my fork, hence the pretty_print_arg in the first traceback.  The second issue you've already fixed as well: https://github.com/cuckoobox/cuckoo/blob/master/lib/cuckoo/core/plugins.py#L438 only the third one (might) need fixed for you as well.

**Comment by galaftion** [comment]
main stream v1.2 and community supported signatures. Some modules I got
from other contributors. I did not personally do any code changes (not a
programmer by any means). Thank you for taking the time to get back to me.

**Comment by galaftion** [comment]
correct, using yours and some others as well. and you guys are doing an
amazing job. I am impressed and thankful for this awesome tool.

**Comment by botherder** [comment]
Closing as unrelated to the project.
