### ISSUE TITLE
Could not import settings 'web.settings'

### ISSUE THREAD

**Issue by Sunrel** [cuckoobox/cuckoo#630]
When I run 

    python /home/sunrel/cuckoo/web/manage.py runserver 0.0.0.0:8085

I get this:

    Traceback (most recent call last):
      File "cuckoo/web/manage.py", line 14, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
        utility.execute()
      File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 261, in fetch_command
        commands = get_commands()
      File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 107, in get_commands
        apps = settings.INSTALLED_APPS
      File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
        self._setup(name)
      File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
        self._wrapped = Settings(settings_module)
      File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
        % (self.SETTINGS_MODULE, e)

    ImportError: Could not import settings 'web.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named lib.cuckoo.common.config

However, when I run the command "python manage.py runserver 0.0.0.0:8085" inside the web folder, it runs perfectly fine. I'm not understanding the error above.

**Comment by KillerInstinct** [comment]
This is due to how pathing works, you need to be running manage.py from the same directory, otherwise https://github.com/cuckoobox/cuckoo/blob/master/web/manage.py#L10 won't be pathed correctly.

**Comment by jbremer** [comment]
What @KillerInstinct said - for now one has to `cd` into the actual `web/` directory.
This should be improved in the future, but for now closing as "feature" - sorry for that ;)

**Comment by ninyesiga** [comment]
@jbremer  that same problem has been disturbing me
How can i solve it

**Comment by jbremer** [comment]
As my last comment said, `cd web/ && python web.py manage`?

**Comment by ninyesiga** [comment]
thank you

**Comment by ninyesiga** [comment]
Hello , i have been having this error while running cuckoo analysis. i do
no how i can solve it.
i help attached a screen shot of the error


Your help is highly appreciated
Thanks

Error
[lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: Analysis
failed: The package "modules.packages.exe" start function raised an error:
Unable to execute the initial process, analysis aborted.
Traceback (most recent call last):
  File "C:\fujkjd\analyzer.py", line 778, in <module>
    success = analyzer.run()
  File "C:\fujkjd\analyzer.py", line 626, in run
    (package_name, e)
CuckooError: The package "modules.packages.exe" start function raised an
error: Unable to execute the initial process analysis aborted.

​

**Comment by doomedraven** [comment]
Hash? Cuckoo version?
