### ISSUE TITLE
VMWare snapshots with accents make cuckoo backtrace

### ISSUE THREAD

**Issue by trou** [cuckoobox/cuckoo#640]
My VM has accents in some snapshots name, and it makes Python barf on "vmrun listSnapshots" output :
```python
Traceback (most recent call last):
  File "./cuckoo.py", line 117, in <module>
    cuckoo_main(max_analysis_count=args.max_analysis_count)
  File "./cuckoo.py", line 87, in cuckoo_main
    sched.start()
  File "/home/raph/tools/reverse/cuckoo/lib/cuckoo/core/scheduler.py", line 535, in start
    self.initialize()
  File "/home/raph/tools/reverse/cuckoo/lib/cuckoo/core/scheduler.py", line 503, in initialize
    machinery.initialize(machinery_name)
  File "/home/raph/tools/reverse/cuckoo/lib/cuckoo/common/abstracts.py", line 87, in initialize
    self._initialize_check()
  File "/home/raph/tools/reverse/cuckoo/modules/machinery/vmware.py", line 40, in _initialize_check
    self._check_snapshot(vmx_path, snapshot)
  File "/home/raph/tools/reverse/cuckoo/modules/machinery/vmware.py", line 74, in _check_snapshot
    return snapshot in output
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 86: ordinal not in range(128)
```
Ugly fix : 
```diff
diff --git a/modules/machinery/vmware.py b/modules/machinery/vmware.py
index bfd80a6..57bed6c 100644
--- a/modules/machinery/vmware.py
+++ b/modules/machinery/vmware.py
@@ -66,6 +66,7 @@ class VMware(Machinery):
                                  stdout=subprocess.PIPE,
                                  stderr=subprocess.PIPE)
             output, _ = p.communicate()
+            output = output.decode('utf-8')
         except OSError as e:
             raise CuckooMachineError("Unable to get snapshot list for %s. "
                                      "Reason: %s" % (vmx_path, e))
```

**Comment by botherder** [comment]
Holy shit, colors in the ticket.
Anyway, thanks for the report. We'll look into it.

**Comment by jbremer** [comment]
The fix seems fine to me. Especially since it would appear `vmrun` returns utf8 data.
