### ISSUE TITLE
travis-ci missing necessary imports 

### ISSUE THREAD

**Issue by PickmanSec** [cuckoobox/cuckoo#645]
RROR: Failure: ImportError (No module named yaml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/cuckoobox/cuckoo/tests/test_apicalls.py", line 11, in <module>
    from analyzer.darwin.lib.dtrace.apicalls import *
  File "/home/travis/build/cuckoobox/cuckoo/analyzer/darwin/lib/dtrace/apicalls.py", line 13, in <module>
    from autoprobes import generate_probes
  File "/home/travis/build/cuckoobox/cuckoo/analyzer/darwin/lib/dtrace/autoprobes.py", line 6, in <module>
    import yaml
ImportError: No module named yaml
======================================================================
ERROR: test suite for <class 'test_cuckoo.CuckooTests'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/travis/build/cuckoobox/cuckoo/tests/test_cuckoo.py", line 100, in setUpClass
    cls.launch_cuckoo()
  File "/home/travis/build/cuckoobox/cuckoo/tests/test_cuckoo.py", line 134, in launch_cuckoo
    raise Exception("Cuckoo failed to launch. Try scripts/bootstrap_host.sh")
Exception: Cuckoo failed to launch. Try scripts/bootstrap_host.sh
======================================================================
ERROR: test suite for <class 'test_dtruss.TestDtruss'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/travis/build/cuckoobox/cuckoo/tests/common.py", line 19, in setUpClass
    raise Exception("%s: dtrace-based test suites must be run on OS X" % cls.__name__)
Exception: TestDtruss: dtrace-based test suites must be run on OS X
======================================================================
ERROR: test suite for <class 'test_ipconnections.TestIpconnections'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/travis/build/cuckoobox/cuckoo/tests/common.py", line 19, in setUpClass
    raise Exception("%s: dtrace-based test suites must be run on OS X" % cls.__name__)
Exception: TestIpconnections: dtrace-based test suites must be run on OS X
======================================================================
ERROR: Failure: ImportError (No module named yaml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/cuckoobox/cuckoo/tests/test_packages.py", line 8, in <module>
    from analyzer.darwin.lib.core.packages import *
  File "/home/travis/build/cuckoobox/cuckoo/analyzer/darwin/lib/core/packages.py", line 6, in <module>
    from ..dtrace.apicalls import apicalls
  File "/home/travis/build/cuckoobox/cuckoo/analyzer/darwin/lib/dtrace/apicalls.py", line 13, in <module>
    from autoprobes import generate_probes
  File "/home/travis/build/cuckoobox/cuckoo/analyzer/darwin/lib/dtrace/autoprobes.py", line 6, in <module>
    import yaml
ImportError: No module named yaml
======================================================================
ERROR: Failure: ImportError (No module named yaml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/cuckoobox/cuckoo/tests/test_probesgenerator.py", line 13, in <module>
    from analyzer.darwin.lib.dtrace.autoprobes import generate_probes
  File "/home/travis/build/cuckoobox/cuckoo/analyzer/darwin/lib/dtrace/autoprobes.py", line 6, in <module>
    import yaml
ImportError: No module named yaml
----------------------------------------------------------------------
Ran 57 tests in 2.474s
FAILED (errors=6)
The command "nosetests" exited with 1.
Done. Your build exited with 1.

**Comment by botherder** [comment]
Fixed. Thank you.
