### ISSUE TITLE
Error in BehaviorAnalysis on _api_CoCreateInstance

### ISSUE THREAD

**Issue by Popof** [cuckoobox/cuckoo#673]
I obtained this error during api call analysis while analysing a sample : 
```python
2015-10-29 17:15:09,704 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "BehaviorAnalysis" for task #1:
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo/lib/cuckoo/core/plugins.py", line 211, in process
    data = current.run()
  File "/home/cuckoo/cuckoo/modules/processing/behavior.py", line 313, in run
    for event in handler.parse(path):
  File "/home/cuckoo/cuckoo/modules/processing/platform/windows.py", line 95, in parse
    res = reconstructor.process_apicall(event)
  File "/home/cuckoo/cuckoo/modules/processing/platform/windows.py", line 133, in process_apicall
    return fn(event["return_value"], event["arguments"])
  File "/home/cuckoo/cuckoo/modules/processing/platform/windows.py", line 289, in _api_CoCreateInstance
    ("guid", arguments["clsid"]),
KeyError: 'clsid'
```

**Comment by jbremer** [comment]
Please update your monitoring binaries by running `./utils/community.py -wafb monitor` or `./utils/community.py -wafb 2.0` if you're also interested in over 300 signatures ;-)
