### ISSUE TITLE
Django web server Broken pipe when connecting to mongoDB

### ISSUE THREAD

**Issue by sarcarx** [cuckoobox/cuckoo#710]
I have the following error when analysing an executable, it seems cuckoo cannot properly connect to mongodb
```
Broken pipe from ('127.0.0.1', 36040)
Internal Server Error: /analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/home/sarcarx/cuckoo/web/analysis/views.py", line 159, in index
    new = get_analysis_info(db, task=task)
  File "/home/sarcarx/cuckoo/web/analysis/views.py", line 82, in get_analysis_info
    }, sort=[("_id", pymongo.DESCENDING)]
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 798, in find_one
    for result in cursor.limit(-1):
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 977, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 902, in _refresh
    self.__read_preference))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 813, in __send_message
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 728, in _send_message_with_response
    server = topology.select_server(selector)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 121, in select_server
    address))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 97, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused
```
on cuckoo.py hand I have 
```
2015-12-22 17:58:50,255 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/home/sarcarx/cuckoo/lib/cuckoo/core/plugins.py", line 623, in process
    current.run(self.results)
  File "/home/sarcarx/cuckoo/modules/reporting/mongodb.py", line 110, in run
    if "cuckoo_schema" in self.db.collection_names():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 488, in collection_names
    ReadPreference.PRIMARY) as (sock_info, slave_okay):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 699, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 663, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 121, in select_server
    address))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 97, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused
```
Any idea?

**Comment by sarcarx** [comment]
Nevermind, had wrong permissions on /var/log/mongodb
